# Generated by Django 5.2.8 on 2025-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
