# Generated by Django 5.2.8 on 2025-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='notas',
        ),
        migrations.AddField(
            model_name='alumno',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
